-- Users table
-- Stores user authentication information
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Create index on username for faster lookups
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

-- Insert default admin user
-- Password: admin123 (MD5 with salt will be applied by backend on first run)
-- This is a placeholder, actual hash will be generated by the application
INSERT OR IGNORE INTO users (id, username, password_hash, salt) 
VALUES (1, 'admin', '', '');

